[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "peppo"
version = "0.1.0"
description = "Python Performance POrtability framework"
authors = [
	{ name = "Mei Matteo", email = "teomei68@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.9"

# runtime dependencies
dependencies = [
]

